pub const UNAUTHORIZED_ACCESS:&str="UNAUTHORIZED_ACCESS";
pub const FORBIDDEN_ACCESS:&str="FORBIDDEN_ACCESS";
pub const RESOURCE_CONFLICT:&str="RESOURCE_CONFLICT";
pub const UNPROCESSABLE_ENTITY:&str="UNPROCESSABLE_ENTITY";
pub const FAILED_TO_CONNECT:&str="FAILED_TO_CONNECT";
pub const UNKNOWN_ERROR:&str="UNKNOWN_ERROR";
pub const INVALID_OPERATION:&str="INVALID_OPERATION";
pub const RESOURCE_NOT_FOUND:&str="RESOURCE_NOT_FOUND";